In [2]:
import nltk                         # NLP toolbox
from os import getcwd
import pandas as pd                 # Library for Dataframes 
from nltk.corpus import twitter_samples 
import matplotlib.pyplot as plt     # Library for visualization
import numpy as np                  # Library for math functions

from utils import process_tweet, build_freqs # Our functions for NLP

In [14]:
# load the NLTK sample dataset - splitting training as 4000 and testing as 1000

# select the set of positive and negative tweets
all_positive_tweets = twitter_samples.strings('positive_tweets.json')
all_negative_tweets = twitter_samples.strings('negative_tweets.json')

# split the data into two pieces, one for training and one for testing (validation set) 
train_pos  = all_positive_tweets[:4000]
train_neg  = all_negative_tweets[:4000]

train_x = train_pos + train_neg 

print("Number of tweets: ", len(train_x))

Number of tweets:  8000


In [26]:
# Extract the features from all the tweets and store the resultant positive and 
# negative sentiment (retrieved from dictionary lookup) in a dataframe

tweets = train_pos + train_neg
labels = np.append(np.ones((len(train_pos),1)), np.zeros((len(train_neg),1)), axis = 0)

freqs = build_freqs(tweets, labels)

# For each of the tweets - extract the features

# create a dataframe to hold the extracted features
data = pd.DataFrame(columns = ['bias', 'positive', 'negative'])
tweets = train_pos + train_neg 

debugon = 0

# Go through all the words in each tweet                
for tweet in tweets:

    # initialize positive and negative counts
    pos = 0
    neg = 0
    
    if (debugon == 1):
        print(tweet)
    
    # go through all the words in a tweet and accumulate pos and neg
    for word in process_tweet(tweet):

        # retrieve number of positive counts
        if (word, 1) in freqs:
            pos = pos + freqs[(word, 1)]
        
        # retrieve number of negative counts
        if (word, 0) in freqs:
            neg = neg + freqs[(word, 0)]

        if (debugon == 1):
            print(word, pos, neg)
        
    # append the word counts to the table
    df2 = {'bias':1, 'positive':pos, 'negative':neg}
    data = data.append(df2, ignore_index=True)
    
data

#process_tweet(tweets[0])

bias positive negative
0       1     3020       61
1       1     3573      444
2       1     3005      115
3       1     2862        4
4       1     3119      225
...   ...      ...      ...
7995    1       29     3706
7996    1       62      323
7997    1      144      783
7998    1      205     3890
7999    1      189     3974

[8000 rows x 3 columns]

In [29]:
X = data[['bias', 'positive', 'negative']].values
Y = labels.

print(X.shape) # Print the shape of the X part
print(X) # Print some rows of X

print(Y)

(8000, 3)
[[1 3020 61]
 [1 3573 444]
 [1 3005 115]
 ...
 [1 144 783]
 [1 205 3890]
 [1 189 3974]]
[[1.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]]


In [ ]:
theta = [7e-08, 0.0005239, -0.00055517]

